name: Using caches

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@3.3.2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          pwd
          chmod +x generate-primes.sh
          ./generate-primes.sh
          cat prime-numbers
