name: Containers!

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: using containers
        run: sudo docker run --rm -v "$PWD":/workdir -w /workdir centos:latest ls -laR
