name: Using custom debug messages

on:
  workflow_dispatch:

env:
  MYVAR: ${{ secrets.ACTIONS_STEP_DEBUG }}

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - echo "My var is: " $MYVAR
