name: Working with actions types

on:
  issues:
    types:
      - opened
      - edited
      - closed

jobs:
  notify-for-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Something happened with an issue"
