name: Install tools

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Install tree
        run: |
          yum update
          yum install -y tree
      - name: Execute tree
        run: time tree | tree -L 2 /
