name: Install tools

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Install tree
        run: |
          yum check-update
          sudo yum install -y tree
      - name: Execute tree
        run: tree -L 2 /
