name: Simple Go Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: '1.15.1'
      - run: go run hello-world.go
