name: Verify file

on:
  push:
  pull_request:

jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    runs-on: ubuntu-latest
    if: ${{ vars.EXEC_WF == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "File to check is: " ${{ vars.FILE_TO_CHECK }}
