name: My Composite Action

on:
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'

jobs:
  count-args:
    runs-on: ubuntu-latest
    env:
      MYARGS: ${{ github.event.inputs.myValues }}
    steps:
      - id: report-count
        uses: nay43/my-composite-action@v1
        with:
          arguments-to-count: $MYARGS
      - shell: bash
        run: |
          echo "Args to count: $MYARGS"
          echo "Total count: ${{ steps.report-count.outputs.arg-count }}"
