name: Using artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python hello_world.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-python
          path: hello_world.py
