name: My Composite Action

on:
  workflow_dispatch:

jobs:
  count-args:
    runs-on: ubuntu-latest
    steps:
      - id: report-count
        uses: nay43/my-composite-action@v1
        with:
          arguments-to-count: 'Hello Hello World'
      - shell: bash
        run: echo "Total count: ${{ steps.report-count.outputs.arg-count }}"
